version: "3.7"
services:
    web:
        build: .
        depends_on:
            - db
        ports:
            - "80:80"
            - "443:443"
        environment:
            - "DB_SERVER=db"
            - "DB_USER=root"
            - "DB_PASSWORD=123"
            - "DB_NAME=demo"
    db:
        image: mariadb:latest
        environment:
            - "MYSQL_ROOT_PASSWORD=123"
        ports:
            - "3306:3306"
